# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\code\PyCharm\Project\PyQt\ui_18.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(730, 293)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 70, 72, 15))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 120, 72, 15))
        self.label_2.setObjectName("label_2")
        self.InfoBrowser = QtWidgets.QTextBrowser(Form)
        self.InfoBrowser.setGeometry(QtCore.QRect(260, 50, 451, 192))
        self.InfoBrowser.setObjectName("InfoBrowser")
        self.userEdit = QtWidgets.QLineEdit(Form)
        self.userEdit.setGeometry(QtCore.QRect(90, 70, 151, 21))
        self.userEdit.setObjectName("userEdit")
        self.passwordEdit = QtWidgets.QLineEdit(Form)
        self.passwordEdit.setGeometry(QtCore.QRect(90, 120, 151, 21))
        self.passwordEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordEdit.setObjectName("passwordEdit")
        self.loginBtn = QtWidgets.QPushButton(Form)
        self.loginBtn.setGeometry(QtCore.QRect(20, 200, 93, 28))
        self.loginBtn.setObjectName("loginBtn")
        self.forgetBtn = QtWidgets.QPushButton(Form)
        self.forgetBtn.setGeometry(QtCore.QRect(150, 200, 93, 28))
        self.forgetBtn.setObjectName("forgetBtn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "用户名："))
        self.label_2.setText(_translate("Form", "密码："))
        self.loginBtn.setText(_translate("Form", "登录"))
        self.forgetBtn.setText(_translate("Form", "忘记密码"))
