# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\code\PyCharm\Project\PyQt\ui_17.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(80, 100, 251, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(60, 180, 291, 30))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Btn_1 = QtWidgets.QPushButton(self.widget)
        self.Btn_1.setObjectName("Btn_1")
        self.horizontalLayout.addWidget(self.Btn_1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.Btn_2 = QtWidgets.QPushButton(self.widget)
        self.Btn_2.setObjectName("Btn_2")
        self.horizontalLayout.addWidget(self.Btn_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Btn_1.setText(_translate("Form", "按钮1-卡"))
        self.Btn_2.setText(_translate("Form", "按钮2-不卡"))
